// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package kr.com.rts.proto;

public final class HelloPrt {
  private HelloPrt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocc_RequestMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocc_RequestMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocc_ResponseMessageStyle1_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocc_ResponseMessageStyle1_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocc_ResponseMessageStyle2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocc_ResponseMessageStyle2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\007protocc\"9\n\016RequestMessage\022" +
      "\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005price\030\003 \001(\002" +
      "\"7\n\025ResponseMessageStyle1\022\016\n\006result\030\001 \001(" +
      "\t\022\016\n\006status\030\002 \001(\t\"y\n\025ResponseMessageStyl" +
      "e2\022\016\n\006result\030\001 \001(\t\022\016\n\006status\030\002 \001(\t\022\022\n\nst" +
      "atusCode\030\003 \001(\002\022,\n\013yourRequest\030\004 \001(\0132\027.pr" +
      "otocc.RequestMessage2\240\001\n\016MyProtoService\022" +
      "F\n\013giveMeData1\022\027.protocc.RequestMessage\032" +
      "\036.protocc.ResponseMessageStyle1\022F\n\013giveM" +
      "eData2\022\027.protocc.RequestMessage\032\036.protoc" +
      "c.ResponseMessageStyle2B\036\n\020kr.com.rts.pr" +
      "otoB\010HelloPrtP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protocc_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocc_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocc_RequestMessage_descriptor,
        new java.lang.String[] { "Id", "Name", "Price", });
    internal_static_protocc_ResponseMessageStyle1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocc_ResponseMessageStyle1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocc_ResponseMessageStyle1_descriptor,
        new java.lang.String[] { "Result", "Status", });
    internal_static_protocc_ResponseMessageStyle2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocc_ResponseMessageStyle2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocc_ResponseMessageStyle2_descriptor,
        new java.lang.String[] { "Result", "Status", "StatusCode", "YourRequest", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
