// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package kr.com.rts.proto;

/**
 * Protobuf type {@code protocc.ResponseMessageStyle2}
 */
public  final class ResponseMessageStyle2 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:protocc.ResponseMessageStyle2)
    ResponseMessageStyle2OrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResponseMessageStyle2.newBuilder() to construct.
  private ResponseMessageStyle2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResponseMessageStyle2() {
    result_ = "";
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResponseMessageStyle2();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResponseMessageStyle2(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            result_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          case 29: {

            statusCode_ = input.readFloat();
            break;
          }
          case 34: {
            kr.com.rts.proto.RequestMessage.Builder subBuilder = null;
            if (yourRequest_ != null) {
              subBuilder = yourRequest_.toBuilder();
            }
            yourRequest_ = input.readMessage(kr.com.rts.proto.RequestMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(yourRequest_);
              yourRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.com.rts.proto.HelloPrt.internal_static_protocc_ResponseMessageStyle2_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.com.rts.proto.HelloPrt.internal_static_protocc_ResponseMessageStyle2_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.com.rts.proto.ResponseMessageStyle2.class, kr.com.rts.proto.ResponseMessageStyle2.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private volatile java.lang.Object result_;
  /**
   * <code>string result = 1;</code>
   * @return The result.
   */
  public java.lang.String getResult() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      result_ = s;
      return s;
    }
  }
  /**
   * <code>string result = 1;</code>
   * @return The bytes for result.
   */
  public com.google.protobuf.ByteString
      getResultBytes() {
    java.lang.Object ref = result_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      result_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUSCODE_FIELD_NUMBER = 3;
  private float statusCode_;
  /**
   * <code>float statusCode = 3;</code>
   * @return The statusCode.
   */
  public float getStatusCode() {
    return statusCode_;
  }

  public static final int YOURREQUEST_FIELD_NUMBER = 4;
  private kr.com.rts.proto.RequestMessage yourRequest_;
  /**
   * <code>.protocc.RequestMessage yourRequest = 4;</code>
   * @return Whether the yourRequest field is set.
   */
  public boolean hasYourRequest() {
    return yourRequest_ != null;
  }
  /**
   * <code>.protocc.RequestMessage yourRequest = 4;</code>
   * @return The yourRequest.
   */
  public kr.com.rts.proto.RequestMessage getYourRequest() {
    return yourRequest_ == null ? kr.com.rts.proto.RequestMessage.getDefaultInstance() : yourRequest_;
  }
  /**
   * <code>.protocc.RequestMessage yourRequest = 4;</code>
   */
  public kr.com.rts.proto.RequestMessageOrBuilder getYourRequestOrBuilder() {
    return getYourRequest();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getResultBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, status_);
    }
    if (statusCode_ != 0F) {
      output.writeFloat(3, statusCode_);
    }
    if (yourRequest_ != null) {
      output.writeMessage(4, getYourRequest());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getResultBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, status_);
    }
    if (statusCode_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, statusCode_);
    }
    if (yourRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getYourRequest());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.com.rts.proto.ResponseMessageStyle2)) {
      return super.equals(obj);
    }
    kr.com.rts.proto.ResponseMessageStyle2 other = (kr.com.rts.proto.ResponseMessageStyle2) obj;

    if (!getResult()
        .equals(other.getResult())) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (java.lang.Float.floatToIntBits(getStatusCode())
        != java.lang.Float.floatToIntBits(
            other.getStatusCode())) return false;
    if (hasYourRequest() != other.hasYourRequest()) return false;
    if (hasYourRequest()) {
      if (!getYourRequest()
          .equals(other.getYourRequest())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getResult().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getStatusCode());
    if (hasYourRequest()) {
      hash = (37 * hash) + YOURREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getYourRequest().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.com.rts.proto.ResponseMessageStyle2 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.com.rts.proto.ResponseMessageStyle2 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code protocc.ResponseMessageStyle2}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:protocc.ResponseMessageStyle2)
      kr.com.rts.proto.ResponseMessageStyle2OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.com.rts.proto.HelloPrt.internal_static_protocc_ResponseMessageStyle2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.com.rts.proto.HelloPrt.internal_static_protocc_ResponseMessageStyle2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.com.rts.proto.ResponseMessageStyle2.class, kr.com.rts.proto.ResponseMessageStyle2.Builder.class);
    }

    // Construct using kr.com.rts.proto.ResponseMessageStyle2.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      result_ = "";

      status_ = "";

      statusCode_ = 0F;

      if (yourRequestBuilder_ == null) {
        yourRequest_ = null;
      } else {
        yourRequest_ = null;
        yourRequestBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.com.rts.proto.HelloPrt.internal_static_protocc_ResponseMessageStyle2_descriptor;
    }

    @java.lang.Override
    public kr.com.rts.proto.ResponseMessageStyle2 getDefaultInstanceForType() {
      return kr.com.rts.proto.ResponseMessageStyle2.getDefaultInstance();
    }

    @java.lang.Override
    public kr.com.rts.proto.ResponseMessageStyle2 build() {
      kr.com.rts.proto.ResponseMessageStyle2 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public kr.com.rts.proto.ResponseMessageStyle2 buildPartial() {
      kr.com.rts.proto.ResponseMessageStyle2 result = new kr.com.rts.proto.ResponseMessageStyle2(this);
      result.result_ = result_;
      result.status_ = status_;
      result.statusCode_ = statusCode_;
      if (yourRequestBuilder_ == null) {
        result.yourRequest_ = yourRequest_;
      } else {
        result.yourRequest_ = yourRequestBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.com.rts.proto.ResponseMessageStyle2) {
        return mergeFrom((kr.com.rts.proto.ResponseMessageStyle2)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.com.rts.proto.ResponseMessageStyle2 other) {
      if (other == kr.com.rts.proto.ResponseMessageStyle2.getDefaultInstance()) return this;
      if (!other.getResult().isEmpty()) {
        result_ = other.result_;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      if (other.getStatusCode() != 0F) {
        setStatusCode(other.getStatusCode());
      }
      if (other.hasYourRequest()) {
        mergeYourRequest(other.getYourRequest());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.com.rts.proto.ResponseMessageStyle2 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.com.rts.proto.ResponseMessageStyle2) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object result_ = "";
    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string result = 1;</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string result = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      
      result_ = getDefaultInstance().getResult();
      onChanged();
      return this;
    }
    /**
     * <code>string result = 1;</code>
     * @param value The bytes for result to set.
     * @return This builder for chaining.
     */
    public Builder setResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      result_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 2;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 2;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 2;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 2;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }

    private float statusCode_ ;
    /**
     * <code>float statusCode = 3;</code>
     * @return The statusCode.
     */
    public float getStatusCode() {
      return statusCode_;
    }
    /**
     * <code>float statusCode = 3;</code>
     * @param value The statusCode to set.
     * @return This builder for chaining.
     */
    public Builder setStatusCode(float value) {
      
      statusCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float statusCode = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatusCode() {
      
      statusCode_ = 0F;
      onChanged();
      return this;
    }

    private kr.com.rts.proto.RequestMessage yourRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        kr.com.rts.proto.RequestMessage, kr.com.rts.proto.RequestMessage.Builder, kr.com.rts.proto.RequestMessageOrBuilder> yourRequestBuilder_;
    /**
     * <code>.protocc.RequestMessage yourRequest = 4;</code>
     * @return Whether the yourRequest field is set.
     */
    public boolean hasYourRequest() {
      return yourRequestBuilder_ != null || yourRequest_ != null;
    }
    /**
     * <code>.protocc.RequestMessage yourRequest = 4;</code>
     * @return The yourRequest.
     */
    public kr.com.rts.proto.RequestMessage getYourRequest() {
      if (yourRequestBuilder_ == null) {
        return yourRequest_ == null ? kr.com.rts.proto.RequestMessage.getDefaultInstance() : yourRequest_;
      } else {
        return yourRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.protocc.RequestMessage yourRequest = 4;</code>
     */
    public Builder setYourRequest(kr.com.rts.proto.RequestMessage value) {
      if (yourRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        yourRequest_ = value;
        onChanged();
      } else {
        yourRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.protocc.RequestMessage yourRequest = 4;</code>
     */
    public Builder setYourRequest(
        kr.com.rts.proto.RequestMessage.Builder builderForValue) {
      if (yourRequestBuilder_ == null) {
        yourRequest_ = builderForValue.build();
        onChanged();
      } else {
        yourRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.protocc.RequestMessage yourRequest = 4;</code>
     */
    public Builder mergeYourRequest(kr.com.rts.proto.RequestMessage value) {
      if (yourRequestBuilder_ == null) {
        if (yourRequest_ != null) {
          yourRequest_ =
            kr.com.rts.proto.RequestMessage.newBuilder(yourRequest_).mergeFrom(value).buildPartial();
        } else {
          yourRequest_ = value;
        }
        onChanged();
      } else {
        yourRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.protocc.RequestMessage yourRequest = 4;</code>
     */
    public Builder clearYourRequest() {
      if (yourRequestBuilder_ == null) {
        yourRequest_ = null;
        onChanged();
      } else {
        yourRequest_ = null;
        yourRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.protocc.RequestMessage yourRequest = 4;</code>
     */
    public kr.com.rts.proto.RequestMessage.Builder getYourRequestBuilder() {
      
      onChanged();
      return getYourRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.protocc.RequestMessage yourRequest = 4;</code>
     */
    public kr.com.rts.proto.RequestMessageOrBuilder getYourRequestOrBuilder() {
      if (yourRequestBuilder_ != null) {
        return yourRequestBuilder_.getMessageOrBuilder();
      } else {
        return yourRequest_ == null ?
            kr.com.rts.proto.RequestMessage.getDefaultInstance() : yourRequest_;
      }
    }
    /**
     * <code>.protocc.RequestMessage yourRequest = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        kr.com.rts.proto.RequestMessage, kr.com.rts.proto.RequestMessage.Builder, kr.com.rts.proto.RequestMessageOrBuilder> 
        getYourRequestFieldBuilder() {
      if (yourRequestBuilder_ == null) {
        yourRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            kr.com.rts.proto.RequestMessage, kr.com.rts.proto.RequestMessage.Builder, kr.com.rts.proto.RequestMessageOrBuilder>(
                getYourRequest(),
                getParentForChildren(),
                isClean());
        yourRequest_ = null;
      }
      return yourRequestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:protocc.ResponseMessageStyle2)
  }

  // @@protoc_insertion_point(class_scope:protocc.ResponseMessageStyle2)
  private static final kr.com.rts.proto.ResponseMessageStyle2 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.com.rts.proto.ResponseMessageStyle2();
  }

  public static kr.com.rts.proto.ResponseMessageStyle2 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResponseMessageStyle2>
      PARSER = new com.google.protobuf.AbstractParser<ResponseMessageStyle2>() {
    @java.lang.Override
    public ResponseMessageStyle2 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResponseMessageStyle2(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResponseMessageStyle2> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResponseMessageStyle2> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public kr.com.rts.proto.ResponseMessageStyle2 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

