// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package kr.com.rts.proto;

public interface ResponseMessageStyle3OrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocc.ResponseMessageStyle3)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes file = 3;</code>
   * @return The file.
   */
  com.google.protobuf.ByteString getFile();
}
